sfg.brewery:
    beer-inventory-service-host: http://localhost:8082
    inventory-user: good
    inventory-password: beer

spring:
    application:
        name: beer-service
    datasource:
        initialization-mode: EMBEDDED
        url: jdbc:h2:mem:testdb;MODE=MYSQL
# default for the artemis mq docker
    artemis:
        user: artemis
        password: simetraehcapa
    cache.jcache.config: classpath:ehcache.xml
    h2.console.enabled: true
    zipkin:
        enabled: false
# Spring Data hangs when not set under Spring Boot 2.3.0
    data:
        jpa:
            repositories:
                bootstrap-mode: lazy

logging:
    level:
        guru:
            springframework: debug