version: '3.8'
services:
    jms:
        image: vromero/activemq-artemis
        ports:
            - 8161:8161
            - 61616:61616

    zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411

    eureka:
        image: plambir7/mssc-brewery-eureka
        ports:
            - 8761:8761

    config:
        image: plambir7/mssc-config-server
        ports:
            - 8888:8888
        depends_on:
            - eureka
        environment:
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'

    inventory-service:
        image: plambir7/mssc-beer-inventory-service
        ports:
            - 8082:8082
        depends_on:
            - eureka
            - config
            - jms
        environment:
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
            SPRING_PROFILES_ACTIVE: local-discovery,localmysql
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411
            SPRING_ARTEMIS_HOST: jms
            SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beer_inventory_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        restart: on-failure

    inventory-failover-service:
        image: plambir7/mssc-inventory-failover
        ports:
            - 8083:8083
        environment:
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411

    beer-service:
        image: plambir7/mssc-beer-service
        ports:
            - 8080:8080
        depends_on:
            - eureka
            - config
            - jms
            - inventory-service
        environment:
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
            SPRING_PROFILES_ACTIVE: local-discovery,localmysql
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411
            SPRING_ARTEMIS_HOST: jms
            SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beer_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        restart: on-failure

    order-service:
        image: plambir7/mssc-beer-order-service
        ports:
            - 8081:8081
        depends_on:
            - eureka
            - config
            - jms
            - beer-service
        environment:
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
            SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8080
            SPRING_PROFILES_ACTIVE: local-discovery,localmysql
            SPRING_ZIPKIN_BASEURL: http://zipkin:9411
            SPRING_ARTEMIS_HOST: jms
            SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beer_order_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        restart: on-failure

    gateway:
        image: plambir7/mssc-brewery-gateway
        ports:
            - 9090:9090
        depends_on:
            - eureka
            - config
            - inventory-service
            - inventory-failover-service
            - beer-service
            - order-service
        environment:
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
            EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
            SPRING_PROFILES_ACTIVE: local-discovery
        restart: on-failure
